### PR TITLE
Add DEBUG statements to --delete-unmanaged-zones

### PR DESCRIPTION
**Pull request by tlimoncelli**

### CODE REVIEW

**Comment by tlimoncelli** [comment]
@Yannik 

The problem is that `DNSProviderNames` is an empty map. 

I don't understand the logic of your code well enough to provide any advice.


```
DEBUG: Checking provider: "cscglobal_ltom215"
   DEBUG: deployedZones for "cscglobal_ltom215" are [angerona.net answerama.com answerswarm.com arqade.com askdifferent.com askpatents.com askubuntu.com askubuntu.dev basicallymoney.com blogoverflow.com branchesbystackoverflow.co branchesbystackoverflow.com branchesbystackoverflow.io chiphacker.com codeforaliving.io collectivesforstackoverflow.co collectivesforstackoverflow.com collectivesforstackoverflow.io collectivesonstackoverflow.co collectivesonstackoverflow.com collectivesonstackoverflow.io crossvalidated.com derivebystackoverflow.co derivebystackoverflow.com derivebystackoverflow.io dnscontrol.org dnscontroltest-cf.com hashcode.ru hatdash.com isstackoverflowdownforeveryoneorjustme.com mathoverflow.dev miniprofiler.com miyodeya.com ninjawanted.com nothingtoinstall.com packageoverflow.com s.tk seasonedadvice.com secretoverflow.com selfserve-stackexchange.com serverfault.com serverfault.dev sezn.ru skepticexchange.com slackoverflow.com spheresforstackoverflow.co spheresforstackoverflow.com spheresforstackoverflow.io spheresonstackoverflow.co spheresonstackoverflow.com spheresonstackoverflow.io sstatic.dev sstatic.net stack-teams.co stack-teams.dev stackapps.com stackapps.dev stackauth.com stackauth.dev stackauth.site stackblueshift.co stackblueshift.dev stackblueshift.site stackbusiness.co stackbusiness.dev stackbusiness.wtf stackdemonstration.com stackenterprise.co stackenterprise.com stackenterprise.dev stackex.com stackexchange.ca stackexchange.cloud stackexchange.com stackexchange.dev stackkoverflow.com stackmeet.io stackmod.blog stackoverflow-teams.co stackoverflow-teams.dev stackoverflow.adultblock stackoverflow.blog stackoverflow.business stackoverflow.ca stackoverflow.careers stackoverflow.cloud stackoverflow.co stackoverflow.co.il stackoverflow.co.nz stackoverflow.com stackoverflow.com.sg stackoverflow.com.vn stackoverflow.design stackoverflow.dev stackoverflow.email stackoverflow.help stackoverflow.mobi stackoverflow.net stackoverflow.nz stackoverflow.ru stackoverflow.sg stackoverflow.software stackoverflow.tv stackoverflow.vn stackoverflowbusiness.com stackoverflowcareers.com stackoverflowdevinsights.com stackoverflowenterprise.com stackoverflowevents.com stackoverflowforteams.co stackoverflowforteams.com stackoverflowforteams.dev stackoverflowforteams.site stackoverflowforwork.com stackoverflowinfo.com stackoverflowmail.com stackoverflowmeetup.com stackoverflowsolutions.com stackoverflowstore.com stackoverflowteams.co stackoverflowteams.com stackoverflowteams.dev stackoverflowteams.site stackpromos.com stacksnippets.dev stacksnippets.net stacksnippets.site stackstatus.net superuser.com switchboardsforstackoverflow.co switchboardsforstackoverflow.com switchboardsforstackoverflow.io switchboardsonstackoverflow.co switchboardsonstackoverflow.com switchboardsonstackoverflow.io teststackexchange.com teststackoverflow.com teststackoverflow.dev thearqade.com traducir.win trystackoverflowforteams.com upshotbystackoverflow.co upshotbystackoverflow.com upshotbystackoverflow.io vectorbystackoverflow.co vectorbystackoverflow.com vectorbystackoverflow.io yodeya.com zaffreteam.com]
   DEBUG: Checking deployedZone: "angerona.net"
      DEBUG: is zone "angerona.net" managed by provider? "cscglobal_ltom215"
      DEBUG: looping through: map[]
         DEBUG: DNSProviderNames is empty.
   DEBUG: Checking deployedZone: "answerama.com"
      DEBUG: is zone "answerama.com" managed by provider? "cscglobal_ltom215"
      DEBUG: looping through: map[]
         DEBUG: DNSProviderNames is empty.
   DEBUG: Checking deployedZone: "answerswarm.com"
      DEBUG: is zone "answerswarm.com" managed by provider? "cscglobal_ltom215"
      DEBUG: looping through: map[r53:-1]
         DEBUG: Checking "r53" ?? "cscglobal_ltom215"
         DEBUG: NO
Removing from provider cscglobal_ltom215: zone answerswarm.com
   DEBUG: Checking deployedZone: "arqade.com"
      DEBUG: is zone "arqade.com" managed by provider? "cscglobal_ltom215"
      DEBUG: looping through: map[cloudflare4_extras:-1]
         DEBUG: Checking "cloudflare4_extras" ?? "cscglobal_ltom215"
         DEBUG: NO
```

**Comment by Yannik** [comment]
@tlimoncelli can you open a PR against the correct branch `delete-unmanged-zones`? You opened it against `master`. I tried changing that via github, but that didn't work properly.

**Comment by Yannik** [comment]
@tlimoncelli I had a closer look at `DNSProviderNames` being empty. This variable was already present in dnscontrol, I did not introduce it. However, there seems to be some problem with it not being set correctly. (For me, it is not empty, btw!)

It should probably be set by `GetDNSConfig`, however, I am not familiar with that part of dnscontrol, and couldn't find the right point to look. Do you have any idea?

Maybe the problem is in the JS engine part? (I have not clue how that works).

**Comment by Yannik** [comment]
@tlimoncelli On further inspection, I found the `dnscontrol print-ir` function. This should return json looking like this:

```
      "name": "mydomain.com",
      "registrar": "hosting.de",
      "dnsProviders": {
        "hosting.de": -1
      },
```

Can you please check if `dnsProviders` is non-empty for you with this command with the domains you are having problems with?

**Comment by Yannik** [comment]
If it is indeed empty, which I suspect, the function to look at is most likely this:

```
function DnsProvider(name, nsCount) {
    if (typeof nsCount === 'undefined') {
        nsCount = -1;
    }
    return function (d) {
        d.dnsProviders[name] = nsCount;
    };
}
```
in `helpers.js`.

Can you post an example `D(...)` for one of the domains you are having this problem with?

**Pull request closed without merging**
